version: '3.7'

services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: windmillhub
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  hub:
    image: ghcr.io/windmill-labs/windmillhub-ee:main
    privileged: true
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db/windmillhub?sslmode=disable
      - PUBLIC_PRIVATE_HUB=true
      - PUBLIC_APP_URL=${APP_URL}
      - LICENSE_KEY=${LICENSE_KEY}

    depends_on:
      db:
        condition: service_healthy
  caddy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped

    # Configure the mounted Caddyfile and the exposed ports or use another reverse proxy if needed
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./certs:/certs # Provide custom certificate files like cert.pem and key.pem to enable HTTPS - See the corresponding section in the Caddyfile
    ports:
      # To change the exposed port, simply change 80:80 to <desired_port>:80. No other changes needed
      - 80:80
      # - 443:443 # Uncomment to enable HTTPS handling by Caddy
    environment:
      - BASE_URL=":80"
      # - BASE_URL=":443" # uncomment and comment line above to enable HTTPS via custom certificate and key files
      # - BASE_URL=hub.example.com # Uncomment and comment line above to enable HTTPS handling by Caddy

volumes:
  db_data: null
