name: Build and push docker image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v4
        with:
          repository: windmill-labs/windmillhub
          token: ${{ secrets.WINDMILLHUB_GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push privately
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: |
            ${{ steps.metadata.outputs.labels }}
            org.opencontainers.image.licenses=Windmill-Enterprise-License
